### ISSUE TITLE
libfreetype missing architectures

### ISSUE THREAD

**Issue by Boyeen** [JonMackey/SubsetFontCreator#1]
Hi Jon, 
Late to the game but I came across SubsetFontCreator and tried to build it on my M1 Macbook Pro. I get an error for libFreetype. Can you point me in the right direction please?  I'm not sure where to get the source to compile this myself, or have I missed something?

Great work btw.

Thanks,
Tim

**Comment by JonMackey** [comment]
Hi Boyeen, Sorry I wasn't notified there was an issue and just happened to see it.  The library was built using freetype.xcodeproj included in this repository.  I've always had a hard time trying to get it to compile on new versions of Xcode.  Let me know if you can't get it to compile.

I assume you read the build instructions at the end of the ReadMe.  There's a note about the FreeType library.

Jon

**Comment by Boyeen** [comment]
Thanks Jon,
I did see the note and download the FreetType2.9.1  src etc. I chased "implicit function declaration not allowed in C99" compile errors for awhile but I have too much else to do... I was just intrigued by the tool.  Thanks anyway. I do appreciate your efforts.

**Comment by JonMackey** [comment]
Boyeen, I checked in changes to the freetype project.  There was an issue with the prefix header that didn't include the config so there were no definitions for some functions.  The updated app I checked in should run on M1 natively.

**Comment by Boyeen** [comment]
Thanks Jon,
I am excited to check out the tool. I did install it and it runs well on my M1.
